### ISSUE TITLE
admin/users problem

### ISSUE THREAD

**Issue by Mestowaty** [nanostudio-org/nanogp#1]
I was writing a minute ago to you on your page.
When i'm giving authorization to nanogp it shows "{"nano_status":"ok","nano_message":"Authorisation successfully granted."}". But in folder admin there is no such folder as users. i don't know what to do, i think it's problem with mkdir and my chmods but i dont know. 
Thanks for help :)

**Comment by Kris-B** [comment]
Did you find the solution? can you share it?

**Comment by Mestowaty** [comment]
I really don't know what i just did :) 
i think point was in chmod on folder admin. I changed it to 777 and then i create folder 'users' and started authentication. Folder for my user id was maked automatically and now it works really good. Thanks for it!

**Comment by Kris-B** [comment]
ok, I'll add some more error handling
thanks!
