### ISSUE TITLE
Error: no write permissions to folder admin/users

### ISSUE THREAD

**Issue by elivne** [nanostudio-org/nanogp#13]
Hi

Following the instructions closely, in the Grant Authorization stage (last step) I get the following error when trying to open the authorize.php page from my browser:

{"nano_status":"error","nano_message":"Error: no write permissions to folder admin\/users."}

Any ideas?

**Comment by Kris-B** [comment]
hi, which permissions are defined on the following folders:
- admin
- admin/users

**Comment by elivne** [comment]
Thanks for the reply. I tried checking permissions on the folders via ftp but for some reason can't see nor set them. Using FileZilla, when trying to set file permissions I see the command used is SITE CHMOD 755 and then response "500 'SITE': command not understood". Advice?

**Comment by Kris-B** [comment]
It looks like your provider does not allow you to change the permissions with CHMOD.

Can you ask your provider how to change the permissions?

**Comment by elivne** [comment]
I will, thanks. Alternatively, is there a way for me to manually create the needed folder+file for Google Photos?

**Comment by Kris-B** [comment]
Maybe you can try to remove the folders an recreate manually folders `admin/users` and `admin`.
And try the app after that.
But without any guarantee....

**Comment by elivne** [comment]
Similar result: "error on mkdir(admin\/users\/XXXXX):mkdir(): Permission denied" where XXXXX is the user id. I can create that folder manually, then run again and then get "Authorisation successfully granted (userID=XXXXX)." But the folder remains empty, and when opening the gallery page I get "nanogallery2: Could not retrieve Google data. Error: Missing access token. Please grant authorization. [my_nanogallery]"

**Comment by elivne** [comment]
Any way to manually create the access token too?

**Comment by Kris-B** [comment]
maybe but this would be very complicated....

**Comment by elivne** [comment]
OK, will focus on making sure I can set write permission for the folders. Thanks.

**Comment by Kris-B** [comment]
good luck ;-)
