### ISSUE TITLE
nanogallery2: Could not retrieve Google data.

### ISSUE THREAD

**Issue by beamkiller** [nanostudio-org/nanogp#14]
Hi,

Everything worked on the webpage I created for my friend, but now she got this error where the gallery is called. Nothing has changed or modified.

`nanogallery2: Could not retrieve Google data. Error: parsererror, SyntaxError: Unexpected token < readyState=4
getResponseHeader=function (a){var b;if(2===t){if(!j){j={};while(b=Cc.exec(f))j[b[1].toLowerCase()]=b[2]}b=j[a.toLowerCase()]}return null==b?null:b}
getAllResponseHeaders=function (){return 2===t?f:null}
setRequestHeader=function (a,b){var c=a.toLowerCase();return t||(a=s[c]=s[c]||a,r[a]=b),this}
overrideMimeType=function (a){return t||(k.mimeType=a),this}
statusCode=function (a){var b;if(a)if(2>t)for(b in a)q[b]=[q[b],a[b]];else v.always(a[v.status]);return this}
abort=function (a){var b=a||u;return i&&i.abort(b),x(0,b),this}
state=function (){return c}`

Thanks for the help.
Regards,
Peter.

**Comment by Kris-B** [comment]
Hi peter,
can you give me the URL of your page?

**Comment by beamkiller** [comment]
Hi, sure. It's: http://anitasvorenovainteriors.com/projects.html

**Comment by Kris-B** [comment]
can you provide the content of the file `nanogp/admin/config.php` ?

**Comment by beamkiller** [comment]
It's:

`<?php
$cfg_client_id          = 'xxx83-jcbnn64l97uah0m7i3crec9tgnuvqj8b.apps.googleusercontent.com';
$cfg_client_secret      = 'xxxdqjc4wjAdDb2l0vsw9z';
$cfg_max_accounts       = 1;
$cfg_log                = true;
$albums_filter          = ['sauvegarde', 'backup', 'automatické','real'];
?>`

**Comment by Kris-B** [comment]
did you change anything in this file recently ?

**Comment by Kris-B** [comment]
any update ?

**Comment by beamkiller** [comment]
Hi,

no i did not changed anything. The webpage was up almost a year. No changes in nanogp or nanogallery parts :(

I recently changed the cfg_log to see if there is some error but this was only after the error but no log files either 🗡

**Comment by Kris-B** [comment]
calling your nanogp server returns error: `Parse error: syntax error, unexpected '[' in /home/mw009800/anitasvorenovainteriors_com/nanogp/admin/config.php on line 6`

Did you or your hosting provider changed the PHP version on this server?

**Comment by beamkiller** [comment]
No PHP change, there is and was PHP 5.2

**Comment by Kris-B** [comment]
can you update to PHP v5.4 ?

**Comment by beamkiller** [comment]
I have updated to PHP 5.6. Issue resolved :). Thanks 👍
