### ISSUE TITLE
Gallery does not show; error message received

### ISSUE THREAD

**Issue by CGuyDesigns** [nanostudio-org/nanogp#2]
Good Afternoon,

After following your steps i get the message below:
{"nano_status":"error","nano_message":"curl error:Unknown SSL protocol error in connection to www.googleapis.com:443 "}

Then on second try i get the message below:
{"nano_status":"warning","nano_message":"Authorization already granted."}

The gallery does not show on my page:
http://www.islanderinternational.com/photo-gallery.aspx

Did i miss something here? Please assist when you have a moment.

Thanking you,
CGuyDesigns

**Comment by Kris-B** [comment]
Hi,

I just checked your page and found 2 issues:
- jQuery should be loaded only once in your page
- the nanogallery2 option `google2URL` is set to `"http://YOUR_WEB_SERVER/nanogp/nanogp.php"` -> you should set the path to your nanogp installation

Please correct this so I can check further

**Comment by CGuyDesigns** [comment]
Good morning,

Silly me missing that. The update has been made to the photo gallery page.

I commented out the jquery from the top of the page and also updated the url. The other js are for bootstrap.

Thank you for your help. The gallery hasn't appeared though :(

Keep me posted.

Thanking you
CGuyDesigns

**Comment by Kris-B** [comment]
in your page, jQuery must be loaded before jquery.nanogallery2.min.js

Access to `http://www.islanderinternational.com/nanogp/nanogp.php` is not possible:  `500 - Internal server error.`

Please check the `admin/users` folder. Does it contain a sub folder? In this sub-folder do you have the files `token_a.txt` and `token_r.txt` ?

**Comment by CGuyDesigns** [comment]
Hi Kris,

Was this a step i missed? The files i downloaded only had readme.txt in it; i just created and uploaded the files mentioned. (users folder has the two txt files mentioned)

I did the update suggested and now i see some progress. It is looking for the photos but now the server 500 error.

I also checked the page directly and i get this message:
{"nano_status":"error","nano_message":"Missing access token. Please grant authorization."}

Is it possibly an issue with my hosting? I am currently waiting for my hosting they have high caller volume today :( 

Can you confirm though, as far as you see, the code has been implemented correctly as of now?

Thanking you again
CGuyDesigns

**Comment by Kris-B** [comment]
the page is now correctly configured ;-)

Do you also have error 500 when you open page: http://www.islanderinternational.com/nanogp/nanogp.php

to grant authorization , you must open http://www.islanderinternational.com/nanogp/authorize.php
but it will not work if there's any issue to access to your page from internet

**Comment by CGuyDesigns** [comment]
Hi Kris, 

Ok perfect!!! The access was granted for the authorize page, I got that message.

Hmmm now I'm lost

**Comment by CGuyDesigns** [comment]
Hi Kris, 

Ok perfect!!! The access was granted for the authorize page, I got that message.

Now hitting the other page I get the missing tokens. 

Hmmm now I'm lost

**Comment by Kris-B** [comment]
On your web page, please check that the value of the option 'userID'. It must be the same as the folder name in admin/users

**Comment by CGuyDesigns** [comment]
Hey Kris,

Ok i believe this step was not done. The tokens text files were added in the admin > users folder.

I created a folder called tokens and placed it as follows:
admin > users > islander

As suggested i updated the userID to the following:
"userID": "islander"

Now the message is as follows:
nanogallery2: Could not retrieve Google data. Error: Missing access token. Please grant authorization. [my_nanogallery]

Authorization was given so i am unsure if there is another step; message below (http://www.islanderinternational.com/nanogp/authorize.php):
{"nano_status":"warning","nano_message":"Authorization already granted."}

Should there be content in the tokens text files?

 Phew almost there :)

**Comment by Kris-B** [comment]
Please empty the folder admin/users and relaunch authorize.php

À folder will be created, assign his name to 'userID' on your page (it should be a number)

**Comment by CGuyDesigns** [comment]
The authorization happened and i deleted the folder, but the users folder is still empty? It should create the text files on its own, right?

I have a feeling a step is missing :( Is there additional script that should be installed on my server?

I am currently communicating with my hosting company to see if they find anything. I do apologise for the hassle.

Not sure if this is helpful but i have a shared server with GoDaddy, will this work or must it be dedicated?

**Comment by Kris-B** [comment]
after launching authorize.php and after having grant authorization, a sub-folder should be created in `admin/users`

Is this the case or not?

**Comment by CGuyDesigns** [comment]
Het Kris,

That does not happen. I had to create a folder and add the text files.

That's why I am wondering if I missed a step for the server.

I checked with my hosting company and they said all is gd.

**Comment by Kris-B** [comment]
Hi,
Can you please download and install v1.2.0 for a new test?

You may need to manually revoke the authorization. For this, use: https://myaccount.google.com/permissions

**Comment by CGuyDesigns** [comment]
Good Afternoon Kris,

Thanking you again for you assistance :)

I did the update as suggested uploading the files on my host and adjusting the paths:
http://www.islanderinternational.com/photo-gallery.aspx

Ok, this is the page i used for the nano-photogallery on my webpage for the div information in the body:
http://nanogallery2.nanostudio.org/builder.html

Am i not to use this guide?

**Comment by HansLooijen** [comment]
I had the same problem. The problem looks like writing to the server. I modified authorize.php to put the keys in the response and uploaded the files manual. It works! Thanks for this great tool

**Comment by HansLooijen** [comment]
I was to optimistic. After a while I get: 
_nanogallery2: Could not retrieve Google data. Error: Error: could not get a new access token: 400 [my_nanogallery]_
I will follow this item for a new suggestion

**Comment by HansLooijen** [comment]
I found a solution. Another path on the sever was writeable an I moved nanogp to there, The basic is working again. Just have to look at the changed props. But again  thanks for this tooling.

**Comment by CGuyDesigns** [comment]
Good Morning,

I started all over!

- **UPDATE:** deleted old shared albums created a new one in Google Photos
(had to create album as unshared **first** then share the album; i now see my album in builder)
- gave new permissions to builder for new shared album
- removed old permission, got new master files, granted new permissions: http://www.islanderinternational.com/nanogp/authorize.php
(**1st try this message:**
{"nano_status":"error","nano_message":"Could not grant authorization. Curl error:Unknown SSL protocol error in connection to www.googleapis.com:443 "})
(**2nd try this message:**
{"nano_status":"error","nano_message":"error on mkdir(admin\/users\/113715073836200788381):mkdir(): Permission denied"})
(**3rd try this message:**
{"nano_status":"warning","nano_message":"Authorization already granted. To revoke authorization: https:\/\/myaccount.google.com\/permissions"})
- in the admin/users folder the txt files are not created
- **UPDATE:** i still get this error: 500 - Internal server error. (currently checking again with my host)
http://www.islanderinternational.com/nanogp/nanogp.php

Here is my gallery link:
http://www.islanderinternational.com/photo-gallery.aspx

Your assistance to resolve this issue is greatly appreciated.

**Comment by CGuyDesigns** [comment]
Ok after working with **hosting** it has been explained that my folders are **writeable** but somehow the dir is not being created as it should for the tokens that is needed.

**This is the message:**
PHP Warning:  file_get_contents(admin/users//token_a.txt): failed to open stream: No such file or directory in \nanogp\nanogp.php on line 47

**Comment by HansLooijen** [comment]
The pad PHP Warning: file_get_contents(admin/users//token_a.txt is missing the userID between //.
This is the case if called directly.
After authorize you should see the map [userID] with the files token_?.txt.
I modified authorize.php to writetest.php to check the creation of a map was possible.
[writetest.zip](https://github.com/nanostudio-org/nanogp/files/804729/writetest.zip)
You can use it to test that the php proces can indeed create a map. (in my case that was the problem.)

**Comment by CGuyDesigns** [comment]
Hi,

Thank you. Will try this test.

**Comment by Kris-B** [comment]
hey guys, thanks for all these details which will help me to improve this application!

@HansLooijen : I followed your advice and added some more error checks.

Included in release v1.2.3

**Comment by Kris-B** [comment]
@CGuyDesigns : if the authorization is already granted and you want to grant it again, please check the section `Manually revoke authorization` at the bottom of https://github.com/nanostudio-org/nanogp

**Comment by CGuyDesigns** [comment]
@Kris-B

I have been doing these steps and i have been getting this error:
PHP Warning:  file_get_contents(admin/users//token_a.txt): failed to open stream: No such file or directory in G:\PleskVhosts\cguydesigns.com\3I\nanogp\nanogp.php on line 47

http://www.islanderinternational.com/nanogp/nanogp.php

@HansLooijen
I tried your steps and i get the permissions denied error. spoke with my hosting which they have changed permissions and the same:

http://www.islanderinternational.com/nanogp/writetest.php

**Comment by Kris-B** [comment]
on my web server, the folders have permissions 0755 and there's no issue.
what permissions do you have on admin and on admin/users?

**Comment by CGuyDesigns** [comment]
@Kris-B 
Currently chatting with the host again :(

Ok my hosting is a **Windows platform** but has **php enabled 5.4**.

He has set the permissions to **allow** for the nanogp folder and subs.

**Question??** Being that it is **windows platform** is there a possibility the script is looking for **something else**?

**Please let me know.** I am totally lost at this point

**Comment by CGuyDesigns** [comment]
Gd Afternoon @Kris-B 

Just checking in if anything may have come up to resolve this issue i have been having.

**Comment by Kris-B** [comment]
I'm developing on Windows, and deploying on Linux -> Windows should not be the issue.

I just detected a typo in authorize.php -> please check version v1.2.4

**Comment by CGuyDesigns** [comment]
Good Morning @Kris-B 

I am unsure what update was done in your files but it is working!!!!! Yayyy :+1: 

The gallery is loading with no issues and the folder and files are being created.

Thank you for this tool it has been a great help :)

**Comment by Kris-B** [comment]
hi @CGuyDesigns 
Good to hear that it's working now.

@CGuyDesigns and @HansLooijen : many thanks for your feedback to help me solve the issue.

If you enjoy nanogallery, maybe you can leave a review to share your experience: https://nanostudio.typeform.com/to/zyHSZD

Thanks!
Chris
