### ISSUE TITLE
how to hide all automatic backup it shows all images of the account

### ISSUE THREAD

**Issue by petereth** [nanostudio-org/nanogp#4]
Hi!

thank you for that great plugin
i have integrated an account here with the script
http://vs-voelkermarkt4.ksn.at

it works well
but one problem i have

the automatic backup albums should not be viewable - 
http://imgur.com/S69mZgF

as i see here http://nanogpvisibility.herokuapp.com/index.html
automatic backup is not visible 
http://imgur.com/a/G1E9B

here it is not visible 
https://get.google.com/albumarchive/115886251547628748686

how could i hide that i find no solution for the customer it is important that no one could see that

thank you
regards
Peter

**Comment by Kris-B** [comment]
Hi Peter!

You can use the option `blackList`. This will filter out albums containing a keyword in the title.
Example: `blackList: 'scrapbook|profil|sicherung'`

Chris

**Comment by petereth** [comment]
Hi Chris!

thank you, but there is no name with this album i find no album name in german it is:

automatische Sicherung

it means in englisch:

automatic backup

i cannot find anything

and where should i put that into?

Example: blackList: 'scrapbook|profil|sicherung'

thx
Peter

**Comment by Kris-B** [comment]
are you using the builder?

**Comment by petereth** [comment]
yes i have done that

http://nanogallery2.nanostudio.org/builder.html

**Comment by Kris-B** [comment]
use the field `Filter: album names must NOT contain any these keywords`
and define something like: `scrapbook profil sicherung`

**Comment by petereth** [comment]
ok

how could i remove this album id
1000000428748686

it is called
 Automatische Sicherung

also in english i do not know
thx
Peter

**Comment by petereth** [comment]
i have uploaded?
new 
authorize.php
and
nanogp.php
http://www.vs-voelkermarkt4.ksn.at/nanogp/authorize.php

**Comment by petereth** [comment]
but i get no images on
http://www.vs-voelkermarkt4.ksn.at/index.php/bild-galerie

**Comment by petereth** [comment]
ad moment i get this error 
{"nano_status":"warning","nano_message":"Authorization already granted. To revoke authorization: https:\/\/myaccount.google.com\/permissions"}

but i will try later remove all old and make a new google key

**Comment by petereth** [comment]
ok i got it again {"nano_status":"ok","nano_message":"Authorisation successfully granted."}

**Comment by petereth** [comment]
add on for the problem i have

this album id
1000000428748686

it is not a normal album it includes all images that where uploaded

and this album i want to make invisible

that is my problem

i also to not know the name of it because this album was not created it is a backup one

thx
peter

**Comment by CGuyDesigns** [comment]
Gd Morning 

I did notice that i had to create the album as **non shared** first then change to **shared album** and the album was visible in the builder. 

I also added **auto backup** in the textbox: **Filter: album names must NOT contain any these keywords**

Hoping this is helpful.

**Comment by petereth** [comment]
Hi!

thank you very much 

where have you changed that, and what did i have to change?

should i upload all files again?

thank you
regards
Peter

**Comment by CGuyDesigns** [comment]
Hi,

I literally deleted my previously shared album and recreated it as a regular album. Once all the images were uploaded there i then shared the album.

A bit tasking I know. Hopefully someone has a better idea. I don't have that many albums so deleting and recreating was manageable for me. :)

**Comment by petereth** [comment]
Hi,

so i have done that

and define something like: scrapbook profit sicherung

Sicherung was the right one!
thx
Peter

**Comment by Kris-B** [comment]
@petereth , your auto backup album is now hidden, so I'll close this issue.
Thanks @CGuyDesigns for your help!


Concerning the visibility of new albums: I could successfully create a new album in Google Photos and it was immediately visible. I didn't have to play with 'share' / 'not share'.
If you still have difficulties with the visibility of new albums, please open a new case.
Thx!
