### ISSUE TITLE
Is the domain http://nanogallery2.nanostudio.org/builder.html currently down?

### ISSUE THREAD

**Issue by CGuyDesigns** [nanostudio-org/nanogp#5]
Good Morning

Currently i am unable to access the page below:
- http://nanogallery2.nanostudio.org/builder.html

Below is the message i see when i view the page:
> This site can’t be reached
> nanogallery2.nanostudio.org’s server DNS address could not be found.
> Search Google for nanogallery 2 nanostudio org builder
> ERR_NAME_NOT_RESOLVED

On my page i see the following:
- http://www.allianceforaction.com/_events-photo-gallery.php

> nanogallery2: error: no image to process. [my_nanogallery]

Thanking you,
CGuyDesigns

**Comment by CGuyDesigns** [comment]
Hi,

**UPDATE:** All good now!

**Comment by Kris-B** [comment]
Hi, this might have been caused by the today DNS provider switch.
Thanks for the update!
