### ISSUE TITLE
Google Oauth2 401. That’s an error

### ISSUE THREAD

**Issue by lukelee36** [nanostudio-org/nanogp#6]
Hello, 

I tryed many times this tutorial, but I have never done it. I makes everithing like in this tutorial, but every times it shows me this kind of error. Please help me.

Greetings 
John

**Comment by Kris-B** [comment]
Hi John,
When do you get this error? after which command or configuration step?

**Comment by lukelee36** [comment]
Hi Kris-B,
After configure config.php, and when I run https://hoza-photo.cz/nanogp/authorize.php it will shows up.

**Comment by lukelee36** [comment]
Ok I found solution. 
In step, when I have to write adress in Authorized redirect URIs. I need fill adress without authorize.php like that:
 https://hoza-photo.cz/nanogp/
After this it will be OK. 
Thanks for your hard works ;)

Edit:
When I try to click on some photos it will send me 403 error...
https://hoza-photo.cz/jsgalery2.html

**Comment by Kris-B** [comment]
Thanks for the update, but it seems that the configuration is not correct.
You got an error because the access token couldn't be renewed: the refresh token is missing.

To generate a new refresh token:
- clear the folder `admin/users`
- delete application's authorization: https://myaccount.google.com/permissions
- then relaunch: https://hoza-photo.cz/nanogp/authorize.php

PS: please check that you have installed the latest version.

**Comment by lukelee36** [comment]
Yes, I have last version
I tryed this procedure, but result is the same. When I open some photos, then I see error 403. I dont know why didnt shows up environment gallery. I will take me to google website..

**Comment by Kris-B** [comment]
Is it working for about 1 hour?
Do you have a file named token_r.txt in admin.users/nnnnnnnnnn ?
Is it empty?

**Comment by lukelee36** [comment]
The connection to google photos is works. But when I try display some photos (https://hoza-photo.cz/jsgalery2.html#nanogallery/my_nanogallery/6397865133113382113). Its redirect me to new page with 403 error on google. 
Yes, I have file named token_r.txt and NO it isn't empty.

**Comment by Kris-B** [comment]
you didn't mention that you do not display images with nanogallery2...
did you try to share the album in google photos?

**Comment by lukelee36** [comment]
Yes I have share the album. I was figured it out. 
I have this part of code in div: "thumbnailOpenOriginal": true
That was copy from your builder. I removed it and now is everithing allright, thanks for your help and yout work on this beautifull gallery.
