### ISSUE TITLE
Authorized Javascript Origins

### ISSUE THREAD

**Issue by Xarcell** [nanostudio-org/nanogp#7]
I tried setting this up last night and ran into a snag. When in the developer console, selecting "web application", and I'm entering the Authorized Javascript Origins, Google will not accept it. It throws the following error:

> Origin URIs must not contain a path or end with "/": https://xarcell-studios.com/templates/endurance-clients/nanogp/authorize.php

In your screenshot, it seems to accept it just fine, but when I do it, it is not accepted.

![screenshot from 2017-03-15 23-38-39](https://cloud.githubusercontent.com/assets/6114450/23980901/37e56f48-09d9-11e7-906b-bf0a89f1f39a.png)

**Comment by Kris-B** [comment]
There's no javascript. You don't need to restrict the javascipt origins.
Just define the authorized redirect URLs.

**Comment by Xarcell** [comment]
Ok, I was just following what I seen in the screenshots.  I got it working. Nice script.
