### ISSUE TITLE
Google Album not shown

### ISSUE THREAD

**Issue by xherbie** [nanostudio-org/nanogp#9]
Yesterday I started to use this module. After configuring all the things the Google Album was correctly displayed on the website I'm currently working on. But this morning, the album went a away. I have no clue what is going wrong. The URL is http://boutique-sein.ch/aktuelleMode.html. On the debug console I see that the request to google is repsonding with a 404 not found message.

I'm pretty sure that I have nothing changed. I tried to open a new project in the developer console of google but unfortunately the same thing.

Any hints?

Thanks & best regards

**Comment by Kris-B** [comment]
I tried your nanogallery settings on a local web page and it worked without any problem (albums Herbst 2014, Altes ipad....).

I noticed that jquery is included twice in your page. Can you try remove one?

**Comment by xherbie** [comment]
Hi Kris, Ups I made an update. There is one jquery lib left. Unfortunately its not working (look at the error message):

nanogallery2: Could not retrieve Google data. Error: error, error readyState=4
getResponseHeader=function (a){var b;if(2===t){if(!f){f={};while(b=ic.exec(e))f[b[1].toLowerCase()]=b[2]}b=f[a.toLowerCase()]}return null==b?null:b}
getAllResponseHeaders=function (){return 2===t?e:null}
setRequestHeader=function (a,b){var c=a.toLowerCase();return t||(a=s[c]=s[c]||a,r[a]=b),this}
overrideMimeType=function (a){return t||(k.mimeType=a),this}
statusCode=function (a){var b;if(a)if(2>t)for(b in a)q[b]=[q[b],a[b]];else v.always(a[v.status]);return this}
abort=function (a){var b=a||u;return c&&c.abort(b),x(0,b),this}
state=function (){return c}
always=function (){return e.done(arguments).fail(arguments),this}
then=function (){var a=arguments;return n.Deferred(function(c){n.each(b,function(b,f){var g=n.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&n.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}
promise=function (a){return null!=a?n.extend(a,d):d}
pipe=function (){var a=arguments;return n.Deferred(function(c){n.each(b,function(b,f){var g=n.isFunction(a[b])&&a[b];e[f[1]](function(){var a=g&&g.apply(this,arguments);a&&n.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[f[0]+"With"](this===d?c.promise():this,g?[a]:arguments)})}),a=null}).promise()}
done=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
fail=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
progress=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
complete=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
success=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
error=function (){if(h){var c=h.length;!function g(b){n.each(b,function(b,c){var d=n.type(c);"function"===d?a.unique&&k.has(c)||h.push(c):c&&c.length&&"string"!==d&&g(c)})}(arguments),d?f=h.length:b&&(e=c,j(b))}return this}
status=404
statusText=error


URL:https://photos.googleapis.com/data/feed/api/user/102886677843979534697/albumid/6399522631311383089?alt=json&kind=photo&thumbsize=300u,300u,300u,300u,300u,300u,300u,300u,300u,300u&imgmax=d [my_nanogallery]

 When I use http://nanogallery2.nanostudio.org/builder.html the gallery is displayed in the builder. I really don't unterstand why it not works. 

Thanks for your help. The new url for taking look at it is: http://contentx.thinx.ch/m/mandanten/275/topic14814/story48693.html

**Comment by Kris-B** [comment]
to avoid any conflict with other components in your page, I made a codepen with your nanogp instance

https://codepen.io/Kris-B/pen/ZeoLJe

but it's not working...

Can you check that you have a r_token.txt file and that this file is not empty?

**Comment by lukelee36** [comment]
Hi,
Now I have the same problem. Two days ago suddenly the same errors shows me too.

nanogallery2: Could not retrieve Google data. Error: error, error readyState=4
getResponseHeader=function (a){var b;if(k){if(!h){h={};while(b=Bb.exec(g))h[b[1].toLowerCase()]=b[2]}b=h[a.toLowerCase()]}return null==b?null:b}
getAllResponseHeaders=function (){return k?g:null}
setRequestHeader=function (a,b){return null==k&&(a=w[a.toLowerCase()]=w[a.toLowerCase()]||a,v[a]=b),this}
overrideMimeType=function (a){return null==k&&(o.mimeType=a),this}
statusCode=function (a){var b;if(a)if(k)y.always(a[y.status]);else for(b in a)u[b]=[u[b],a[b]];return this}
abort=function (a){var b=a||x;return e&&e.abort(b),A(0,b),this}
state=function (){return d}
always=function (){return f.done(arguments).fail(arguments),this}
catch=function (a){return e.then(null,a)}
pipe=function (){var a=arguments;return r.Deferred(function(b){r.each(c,function(c,d){var e=r.isFunction(a[d[4]])&&a[d[4]];f[d[1]](function(){var a=e&&e.apply(this,arguments);a&&r.isFunction(a.promise)?a.promise().progress(b.notify).done(b.resolve).fail(b.reject):b[d[0]+"With"](this,e?[a]:arguments)})}),a=null}).promise()}
then=function (b,d,e){var f=0;function g(b,c,d,e){return function(){var h=this,i=arguments,j=function(){var a,j;if(!(b=f&&(d!==N&&(h=void 0,i=[a]),c.rejectWith(h,i))}};b?k():(r.Deferred.getStackHook&&(k.stackTrace=r.Deferred.getStackHook()),a.setTimeout(k))}}return r.Deferred(function(a){c[0][3].add(g(0,a,r.isFunction(e)?e:M,a.notifyWith)),c[1][3].add(g(0,a,r.isFunction(b)?b:M)),c[2][3].add(g(0,a,r.isFunction(d)?d:N))}).promise()}
promise=function (a){return null!=a?r.extend(a,e):e}
progress=function (){return f&&(c&&!b&&(h=f.length-1,g.push(c)),function d(b){r.each(b,function(b,c){r.isFunction(c)?a.unique&&j.has(c)||f.push(c):c&&c.length&&"string"!==r.type(c)&&d(c)})}(arguments),c&&!b&&i()),this}
done=function (){return f&&(c&&!b&&(h=f.length-1,g.push(c)),function d(b){r.each(b,function(b,c){r.isFunction(c)?a.unique&&j.has(c)||f.push(c):c&&c.length&&"string"!==r.type(c)&&d(c)})}(arguments),c&&!b&&i()),this}
fail=function (){return f&&(c&&!b&&(h=f.length-1,g.push(c)),function d(b){r.each(b,function(b,c){r.isFunction(c)?a.unique&&j.has(c)||f.push(c):c&&c.length&&"string"!==r.type(c)&&d(c)})}(arguments),c&&!b&&i()),this}
status=404
statusText=error


URL:https://photos.googleapis.com/data/feed/api/user/115302032459925149485/albumid/6399596014342662369?alt=json&kind=photo&thumbsize=300u,300u,300u,300u,300u,300u,300u,300u,300u,300u&imgmax=d [my_nanogallery]

But for me it's a different course. My gallery is shows up, but after I open some album this errors shows up. 

Three days ago everithing was fine. I thinks thats somethink change on the side of Google.

**Comment by Kris-B** [comment]
I just found a bug in v1.2.0
the list of albums should be shown, but not the content of an album.
I'll release a fix shortly
in between, you could downgrade to v1.1.0
sorry for that....

**Comment by Kris-B** [comment]
precision: the bug is in nanogallery2 v1.2.0 - not in nanogp

**Comment by lukelee36** [comment]
Ok, I solved it by that I canceled all your external JS links and use links from my server.

**Comment by xherbie** [comment]
Do you release a new version? After that I install a local version on my server. Thanks for your help. Best regards Herbie

**Comment by Kris-B** [comment]
just released nanogallery2 v1.2.1
